In [1]:
# a python list
list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
# a numpy array
array = np.array([1,2,3])

## Differences between Python List and NumPy Array

In [4]:
# Both are ordered, mutable, duplicate
py_list = [1,1,2,3,3]
np_array = np.array([1,1,2,3,3])

In [5]:
# appending possible with lists
py_list.append(5)

In [6]:
py_list

[1, 1, 2, 3, 3, 5]

In [7]:
# lists can have different types of elements
py_list.append('apple')

In [8]:
py_list

[1, 1, 2, 3, 3, 5, 'apple']

In [9]:
# operations can be done with loops
[i*5 for i in py_list]

[5, 5, 10, 15, 15, 25, 'appleappleappleappleapple']

In [10]:
# operations in arrays are more efficient
np_array * 5

array([ 5,  5, 10, 15, 15])

In [11]:
integers = np.array([10,20,30,40,50])

In [12]:
print(integers)

[10 20 30 40 50]


In [13]:
integers[0]

10

In [14]:
integers.size

5

In [15]:
integers[0]=20

In [16]:
print(integers)

[20 20 30 40 50]


In [17]:
integers[0]=21.5

In [18]:
# Arrays include only same type of elements
print(integers)

[21 20 30 40 50]


## This example is showing how changing the data type can significantly reduce the memory used by a NumPy Array

In [19]:
integers.dtype

dtype('int32')

In [20]:
smallerIntegers = np.array(integers, dtype=np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [21]:
integers.nbytes

20

In [22]:
smallerIntegers.nbytes

5

## Multidimensional Arrays

In [24]:
#this is a two-dimensional array, a matrix
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [25]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
nums[0,0]

1

In [27]:
nums.ndim

2

In [28]:
#this is a three-dimensional array, a tensor
multi_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [29]:
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
multi_arr.ndim

3

## Creating arrays from lists and other Python structures

In [31]:
first_list = [1,2,3,4,5,6,7,8,9,10]

In [32]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [33]:
first_array = np.array(first_list)

In [34]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
second_list = [10,5, -20, 5, 6, 9, -111.6]

In [36]:
second_array = np.array(second_list)

In [37]:
second_array

array([  10. ,    5. ,  -20. ,    5. ,    6. ,    9. , -111.6])

In [38]:
second_array.dtype

dtype('float64')

In [39]:
third_list = ['Anna',12121, 'John', 51212, 'Daist', 56454]

In [41]:
third_array = np.array(third_list)

In [42]:
third_array

array(['Anna', '12121', 'John', '51212', 'Daist', '56454'], dtype='<U11')

In [43]:
first_tuple = (5, 10, 15, 20, 25, 30)

In [44]:
array_from_tuple = np.array(first_tuple)

In [45]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [47]:
multi_dim_list = [[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]]

In [48]:
arr_from_multi_dim_list = np.array(multi_dim_list)

In [49]:
arr_from_multi_dim_list

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]])

## Intrisic NumPy Array Creation

In [56]:
# np.arange(): Creates an array with a sequence of numbers, similar to Python’s built-in range() but returns a NumPy array.

In [51]:
integers_array = np.arange(10)

In [52]:
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
integers_second_array = np.arange(100,130)

In [55]:
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

## Creating Arrays with Constant Values